### PR TITLE
remove and/or clarify use of update, delete, and vacuum in the HAWQ docs

### PR DESCRIPTION
**Pull request by lisakowen**
several doc pages reference the currently unsupported HAWQ update and delete commands.  removed references to these commands in several areas of the docs.

vacuum support in HAWQ is currently applicable only to catalog tables. remove and/or clarify this in several areas of the docs.

### CODE REVIEW

**Comment by lisakowen** [comment]
left the update/delete references in GRANT and REVOKE commands.  it appears you can actually specify them, though i think they are a no-op.

**Comment by lisakowen** [comment]
SELECT ... FOR UPDATE and SELECT ... FOR SHARE support is still a bit unclear in the docs.

**Comment by dyozie** [comment]
This looks great, Lisa.  Just one minor edit - the change to datamgmt/BasicDataOperations.html.md.erb
 has a nearly-repeated sentence re: periodically running vacuum.  Can you edit to remove one of the sentences?  Thx.

**Comment by lisakowen** [comment]
yep, that sentence was on that page twice.  good catch.  i removed it.

**Pull request merged**
