### PR TITLE
Update hawq register for partitioned tables

### PR DESCRIPTION
**Pull request by janebeckman**

### CODE REVIEW

**Comment by dyozie** [comment]
@janebeckman - it seems like this PR has some merge conflicts.  Any idea why that would be the case?

**Comment by janebeckman** [comment]
I've been reviewing these for merge conflicts, and can't seem to find what
the issue is.  My best guess is something was something to do with changes
to do with the --repair option, that were then removed by a later commit
when they removed the option entirely.

**Comment by dyozie** [comment]
Can you resolve the merge conflicts locally and resubmit the PR?

**Comment by janebeckman** [comment]
Closing this pull request to work on figuring why merge conflicts still are flagged, but not showing up when checking files. Will resubmit later.

**Pull request closed without merging**
